spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
    show-sql: true


---

spring:
  profiles:
    active: prod
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
    show-sql: true


---

spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
    show-sql: true
